version: '3'
services:
    db:
        image: mongo
        ports:
            - 27017:27017
    alfred:
        image: gcr.io/mussia6/alfred
        build:
            context: packages/webclients/alfred
            dockerfile: Dockerfile
        container_name: alfred
        environment:
            - NODE_ENV_DOCKER=true
            - DB_USER=admin
            # dev db
            - MONGODB_URI=mongodb://0.0.0.0/jarvis
            - DB_PASSWORD=elmtmVSesRtpz3de
            - DATABASE_URL=@cluster0.xliif.gcp.mongodb.net/
        # local db
        #            - DATABASE_URL=mongodb://db/rt-react
        ports:
            - 3000:3000
        command: npm run start
#        depends_on:
#            - db
#
    batman:
        image: gcr.io/mussia6/batman
        build:
            context: packages/webclients/batman
            dockerfile: Dockerfile
        container_name: batman
        environment:
            - NODE_ENV_DOCKER=true
            - DB_USER=admin
              # dev db
            - MONGODB_URI=mongodb://0.0.0.0/jarvis
            - DB_PASSWORD=elmtmVSesRtpz3de
            - DATABASE_URL=@cluster0.xliif.gcp.mongodb.net/
        #            - DB_PASSWORD=elmtmVSesRtpz3de
        #            - DATABASE_URL=@cluster0.xliif.gcp.mongodb.net/
        # local db
        #            - DATABASE_URL=mongodb://db/rt-react
        ports:
            - 4000:3000
        command: npm run start

    billing:
        image: gcr.io/mussia6/billing
        build:
            context: packages/services/billing
            dockerfile: Dockerfile
            args:
                - modulePath=/packages/services/billing
        container_name: billing
        environment:
            - NODE_ENV_DOCKER=true
#            - PORT=5000
            - DB_USER=admin
            - MONGODB_URI=mongodb://0.0.0.0/jarvis
            - DB_PASSWORD=elmtmVSesRtpz3de
            - DATABASE_URL=@cluster0.xliif.gcp.mongodb.net/
        ports:
            - 5000:8080
        command: npm run start
