version: '3'
services:
    db:
        image: mongo
        ports:
            - 27017:27017
    jarvis:
        image: perimeter81/jarvis
        build:
            context: packages/jarvis
            dockerfile: Dockerfile
        container_name: jarvis
        environment:
            - NODE_ENV_DOCKER=true
            - DB_USER=admin
            # dev db
            - MONGODB_URI=mongodb://0.0.0.0/jarvis
            - DB_PASSWORD=elmtmVSesRtpz3de
            - DATABASE_URL=@cluster0.xliif.gcp.mongodb.net/
        # local db
        #            - DATABASE_URL=mongodb://db/rt-react
        ports:
            - 3000:3000
#            - 4001:4001
#            - 7000:7000
#            - 7070:7070
#        volumes:
#            - ./:/usr/app/src
        command: npm run start
#        depends_on:
#            - db
#
    webclient:
        image: perimeter81/webclient
        build:
            context: packages/webclient
            dockerfile: Dockerfile
        container_name: webclient
        environment:
            - NODE_ENV_DOCKER=true
            - DB_USER=admin
              # dev db
            - MONGODB_URI=mongodb://0.0.0.0/jarvis
            - DB_PASSWORD=elmtmVSesRtpz3de
            - DATABASE_URL=@cluster0.xliif.gcp.mongodb.net/
        #            - DB_PASSWORD=elmtmVSesRtpz3de
        #            - DATABASE_URL=@cluster0.xliif.gcp.mongodb.net/
        # local db
        #            - DATABASE_URL=mongodb://db/rt-react
        ports:
            - 4000:3000
        command: npm run start

    billing:
        image: perimeter81/billing
        build:
            context: packages/services/billing
            dockerfile: Dockerfile
            args:
                - modulePath=/packages/billing
        container_name: billing
        environment:
            - NODE_ENV_DOCKER=true
#            - PORT=5000
            - DB_USER=admin
            - MONGODB_URI=mongodb://0.0.0.0/jarvis
            - DB_PASSWORD=elmtmVSesRtpz3de
            - DATABASE_URL=@cluster0.xliif.gcp.mongodb.net/
        ports:
            - 5000:8080
        command: npm run start
