# openapi2-run.yaml
swagger: '2.0'
info:
  title: aris-api optional-string
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /billing:
    get:
      parameters:
        - in: path
          name: asset
          type: string
          required: true
          description: Name of the asset.
      summary: Assets
      operationId: getAsset
      x-google-backend:
        address: https://billing-iinq65tiba-ew.a.run.app/
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /hello:
    get:
      summary: Cloud Run hello world
      operationId: hello
      x-google-backend:
        address: https://batman-iinq65tiba-ew.a.run.app/api/hello
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /func1:
    get:
      summary: Cloud function func1
      operationId: func1
      x-google-backend:
        address: https://europe-west1-mussia6.cloudfunctions.net/func1
      responses:
        '200':
          description: A successful response
          schema:
            type: string
